### ISSUE TITLE
Request for Documentation Update on How to Use the LlamaTouch Evaluator Module

### ISSUE THREAD

**Issue by lgy0404** [LlamaTouch/LlamaTouch#1]
Hi LlamaTouch Team,

First of all, thank you for developing this interesting project. I am attempting to use the LlamaTouch Evaluator module to access each episode in the dataset, but I noticed that the "How to Use" section in the README file is still marked as TODO. Could you inform me when an update on this part might be available?

I am particularly interested in understanding how to properly utilize the LlamaTouch Evaluator module to access and process tasks within the dataset. Specifically, I would like to know how to load and parse the dataset through the module, as well as how to evaluate and visualize the action sequences.

Could you provide some basic example codes or links to documentation? This would greatly assist users like myself in effectively using your tool.

Looking forward to your response, thank you!

**Comment by lizhang20** [comment]
Thank you for your attention. We will update the doc as soon as possible.

**Comment by lizhang20** [comment]
Sorry for the late response. For your purpose, please check the latest doc at https://github.com/LlamaTouch/LlamaTouch/tree/main/dataset. We added an example script for accessing the dataset and commands for visualizing the UI sequences.

Please ensure you have downloaded the latest LlamaTouch Evaluator module and the dataset. We are happy to take your further feedback. Thanks!
