### ISSUE TITLE
Integrating External Agent Models with LlamaTouch for Automated Success Rate Measurement

### ISSUE THREAD

**Issue by shp216** [LlamaTouch/LlamaTouch#2]
Hello! Thank you for your great research.
I would like to use LlamaTouch to run a different agent model that is not proposed in this paper, but I am not sure how to use it because various settings, including the action space, are different. I want to run an agent from another paper and automatically measure the success rate using LlamaTouch's dataset. Is there a way to do this?

**Comment by lizhang20** [comment]
Hi, thanks for your attention to LlamaTouch. The setup process currently involves a lot of steps. We are working to make it easily deployable and to provide more user-friendly documentation, including how to adapt the action space as you mentioned. We will notify you when we have completed this part (we will provide this ASAP).
